# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_lan.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1329, 804)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 设置 centralwidget 背景颜色为浅蓝色
        self.centralwidget.setStyleSheet("QWidget { background-color: pink; color: darkblue; }")


        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1341, 771))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 850, 230))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_3.setStyleSheet("QGroupBox { border: 2px solid darkblue; }")

        self.rect_frame1 = QtWidgets.QFrame(self.tab)
        self.rect_frame1.setGeometry(QtCore.QRect(10, 5, 850, 25))  # 设置位置和大小
        self.rect_frame1.setStyleSheet("QFrame { "
                              "border: 2px solid darkblue; "
                              "background-color: lightgray; "
                              "border-radius: 5px; "
                              "}")
        # 添加文本
        self.label = QtWidgets.QLabel("数据库", self.rect_frame1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.label.setGeometry(QtCore.QRect(0, 0, 850, 25))  # 设置文本显示区域
        self.label.setStyleSheet("font-weight: bold;")


        # 设置line edit
        self.lineEdit_input = QtWidgets.QLineEdit(self)
        self.lineEdit_input.setGeometry(QtCore.QRect(10, 30, 850, 31))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.lineEdit_input.setStyleSheet("QLineEdit { background-color: lightgray; border: 2px solid darkblue; color: black;}")
        # lineEdit_input移动到右下角
        self.lineEdit_input.move(25, 735)
        # 添加回车事件处理
        self.lineEdit_input.returnPressed.connect(self.on_return_pressed)

        # 设置push button提交按钮
        self.pushButton_submit = QtWidgets.QPushButton(self)
        self.pushButton_submit.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.pushButton_submit.move(900, 735)
        # 设置push button提交按钮文本
        self.pushButton_submit.setText("提交")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)

        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 240, 850, 230))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_4.setStyleSheet("QGroupBox { border: 2px solid darkblue; }")

        self.rect_frame2 = QtWidgets.QFrame(self.tab)
        self.rect_frame2.setGeometry(QtCore.QRect(10, 245, 850, 25))  # 设置位置和大小
        self.rect_frame2.setStyleSheet("QFrame { "
                              "border: 2px solid darkblue; "
                              "background-color: lightgray; "
                              "border-radius: 5px; "
                              "}")
        # 添加文本
        self.label = QtWidgets.QLabel("显示区", self.rect_frame2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.label.setGeometry(QtCore.QRect(0, 0, 850, 25))  # 设置文本显示区域
        self.label.setStyleSheet("font-weight: bold;")

        self.textBrowserlog = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowserlog.setGeometry(QtCore.QRect(0, 25, 850, 205))
        self.textBrowserlog.setObjectName("textBrowserlog")

        self.textBrowserlog.setStyleSheet("QWidget { background-color: lightblue; color: darkblue; }")
        self.textBrowserlog.setStyleSheet("QTextBrowser { border: 2px solid darkblue; }")

        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 500, 850, 190))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setStyleSheet("QGroupBox { border: 2px solid darkblue; }")

        self.rect_frame3 = QtWidgets.QFrame(self.tab)
        self.rect_frame3.setGeometry(QtCore.QRect(10, 485, 850, 25))  # 设置位置和大小
        self.rect_frame3.setStyleSheet("QFrame { "
                              "border: 2px solid darkblue; "
                              "background-color: lightgray; "
                              "border-radius: 5px; "
                              "}")
        
        # 添加文本
        self.label = QtWidgets.QLabel("功能区", self.rect_frame3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)  # 文字居中
        self.label.setGeometry(QtCore.QRect(0, 0, 850, 25))  # 设置文本显示区域
        self.label.setStyleSheet("font-weight: bold;")

        self.pushButtonbrowse = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonbrowse.setGeometry(QtCore.QRect(0, 0, 170, 40))
        self.pushButtonbrowse.setObjectName("pushButtonbrowse")

        self.pushButtonclear = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonclear.setGeometry(QtCore.QRect(170, 0, 170, 40))
        self.pushButtonclear.setObjectName("pushButtonclear")

        self.pushButtonselall = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonselall.setGeometry(QtCore.QRect(340, 0, 170, 40))
        self.pushButtonselall.setObjectName("pushButtonselall")

        self.pushButtonload = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonload.setGeometry(QtCore.QRect(510, 0, 170, 40))
        self.pushButtonload.setObjectName("pushButtonload")

        self.pushButtonbrowseLoad = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonbrowseLoad.setGeometry(QtCore.QRect(680, 0, 170, 40))
        self.pushButtonbrowseLoad.setObjectName("pushButtonbrowseLoad")

        self.pushButtonbrowse.setStyleSheet("QPushButton { background-color: darkblue; color: white; }")
        self.pushButtonbrowseLoad.setStyleSheet("QPushButton { background-color: darkblue;  color: white;}")
        self.pushButtonclear.setStyleSheet("QPushButton { background-color: darkblue;  color: white;}")
        self.pushButtonselall.setStyleSheet("QPushButton { background-color: darkblue; color: white; }")
        self.pushButtonload.setStyleSheet("QPushButton { background-color: darkblue;  color: white;}")

        self.comboBoxfiletype = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxfiletype.setGeometry(QtCore.QRect(80, 220, 101, 26))
        self.comboBoxfiletype.setObjectName("comboBoxfiletype")
        self.tabWidget.addTab(self.tab, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 1091, 121))
        self.groupBox_2.setObjectName("groupBox_2")

        '''self.pushButton_confirm_idx = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_confirm_idx.setGeometry(QtCore.QRect(910, 80, 113, 32))
        self.pushButton_confirm_idx.setObjectName("pushButton_confirm_idx")

        self.pushButton_clear_idx = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_clear_idx.setGeometry(QtCore.QRect(910, 30, 113, 31))
        self.pushButton_clear_idx.setObjectName("pushButton_clear_idx")'''

        self.comboBox_wb = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_wb.setGeometry(QtCore.QRect(110, 30, 481, 26))
        self.comboBox_wb.setObjectName("comboBox_wb")
        self.comboBox_ws = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_ws.setGeometry(QtCore.QRect(110, 80, 481, 26))
        self.comboBox_ws.setObjectName("comboBox_ws")

        '''self.label_keyidx = QtWidgets.QLabel(self.groupBox_2)
        self.label_keyidx.setGeometry(QtCore.QRect(610, 30, 91, 31))
        self.label_keyidx.setObjectName("label_keyidx")

        self.label_range = QtWidgets.QLabel(self.groupBox_2)
        self.label_range.setGeometry(QtCore.QRect(610, 80, 91, 31))
        self.label_range.setObjectName("label_range")

        '''
        self.comboBox_x = QtWidgets.QComboBox(self.groupBox_2)
        #self.comboBox_x.setGeometry(QtCore.QRect(730, 30, 71, 26))
        self.comboBox_x.setObjectName("comboBox_x")

        self.comboBox_y = QtWidgets.QComboBox(self.groupBox_2)
        #self.comboBox_y.setGeometry(QtCore.QRect(800, 30, 91, 26))
        self.comboBox_y.setObjectName("comboBox_y")
        

        self.comboBox_r1 = QtWidgets.QComboBox(self.groupBox_2)
        #self.comboBox_r1.setGeometry(QtCore.QRect(730, 80, 71, 26))
        self.comboBox_r1.setObjectName("comboBox_r1")

        self.comboBox_r2 = QtWidgets.QComboBox(self.groupBox_2)
        #self.comboBox_r2.setGeometry(QtCore.QRect(800, 80, 91, 26))
        self.comboBox_r2.setObjectName("comboBox_r2")

        self.checkBox_book = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_book.setGeometry(QtCore.QRect(10, 30, 81, 31))
        self.checkBox_book.setChecked(False)
        self.checkBox_book.setObjectName("checkBox_book")

        self.checkBox_sheet = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_sheet.setGeometry(QtCore.QRect(10, 80, 81, 31))
        self.checkBox_sheet.setChecked(False)
        self.checkBox_sheet.setObjectName("checkBox_sheet")

        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 139, 1111, 591))
        self.groupBox_5.setObjectName("groupBox_5")

        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget.setGeometry(QtCore.QRect(0, 30, 1111, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")

        # 添加AI提示框
        self.groupBox_ai = QtWidgets.QGroupBox(self.tab)
        self.groupBox_ai.setGeometry(QtCore.QRect(870, 10, 430, 680))  # 增加宽度,左移
        self.groupBox_ai.setObjectName("groupBox_ai")
        self.groupBox_ai.setStyleSheet("QGroupBox { border: 2px solid darkblue; }")

        # AI提示框标题
        self.rect_frame_ai = QtWidgets.QFrame(self.tab)
        self.rect_frame_ai.setGeometry(QtCore.QRect(870, 5, 430, 25))
        self.rect_frame_ai.setStyleSheet("QFrame { "
                              "border: 2px solid darkblue; "
                              "background-color: lightgray; "
                              "border-radius: 5px; "
                              "}")
        
        self.label_ai = QtWidgets.QLabel("AI 智能助手", self.rect_frame_ai)
        self.label_ai.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ai.setGeometry(QtCore.QRect(0, 0, 430, 25))
        self.label_ai.setStyleSheet("font-weight: bold;")

        # AI提示文本框
        self.textBrowser_ai = QtWidgets.QTextBrowser(self.groupBox_ai)
        self.textBrowser_ai.setGeometry(QtCore.QRect(10, 30, 410, 640))
        self.textBrowser_ai.setObjectName("textBrowser_ai")
        self.textBrowser_ai.setStyleSheet(
            "QTextBrowser { background-color: #f0f8ff; border: 2px solid darkblue; }"
        )

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1129, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #MainWindow.setWindowTitle(_translate("MainWindow", "Mini DBMS by group 10"))
        #self.groupBox_3.setTitle(_translate("MainWindow", "数据库"))
        #self.groupBox_4.setTitle(_translate("MainWindow", "显示区"))
        #self.groupBox.setTitle(_translate("MainWindow", "功能区"))


        self.pushButtonbrowse.setText(_translate("MainWindow", "数据库"))
        self.pushButtonbrowseLoad.setText(_translate("MainWindow", "加载excel"))
        self.pushButtonclear.setText(_translate("MainWindow", "清除"))
        self.pushButtonselall.setText(_translate("MainWindow", "全选"))
        self.pushButtonload.setText(_translate("MainWindow", "加载"))
        

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        index = self.tabWidget.indexOf(self.tab)
        self.tabWidget.tabBar().setTabTextColor(index, Qt.white) 
        #self.tabWidget.setStyleSheet("QTabWidget { background-color: lightgray; color: white; }")

        self.groupBox_2.setTitle(_translate("MainWindow", "参数配置"))
        #self.pushButton_confirm_idx.setText(_translate("MainWindow", "confirm"))
        #self.pushButton_clear_idx.setText(_translate("MainWindow", "clear"))
        #self.label_keyidx.setText(_translate("MainWindow", "  idx"))
        #self.label_range.setText(_translate("MainWindow", " range"))
        self.checkBox_book.setText(_translate("MainWindow", "books"))
        self.checkBox_sheet.setText(_translate("MainWindow", "sheets"))
        self.groupBox_5.setTitle(_translate("MainWindow", "excel显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data"))
        index_2= self.tabWidget.indexOf(self.tab_2)
        self.tabWidget.tabBar().setTabTextColor(index_2, Qt.white)
        self.groupBox_ai.setTitle("")